[package]
name = "uwb-anchor"
version = "0.1.0"
authors = ["Nicolas Farabegoli <nicolas.farabegoli@gmail.com>"]
edition = "2021"

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
panic-probe = { workspace = true }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-hal-bus = { workspace = true }

# Embassy dependencies
embassy-stm32 = { workspace = true }
embassy-sync = { workspace = true }
embassy-executor = { workspace = true }
embassy-time = { workspace = true }
embassy-usb = { workspace = true }
embassy-embedded-hal = { workspace = true }
embassy-futures = { workspace = true }
heapless = { workspace = true }
critical-section = { workspace = true }

# Defmt for logging
defmt = { workspace = true }
defmt-rtt = { workspace = true }

dw1000 = { workspace = true }

[build-dependencies]
reqwest = { workspace = true }

[workspace]
members = ["tag"]
resolver = "2"

[workspace.dependencies]
cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
embedded-hal = "1.0.0"
embedded-hal-async = { version = "1.0" }
embedded-hal-bus = { version = "0.3.0", features = ["async"] }

# Embassy dependencies
embassy-stm32 = { version = "0.4.0", features = [ "stm32l432kc", "defmt", "unstable-pac", "memory-x", "time-driver-tim1", "exti", "chrono"] }
embassy-sync = { version = "0.7.2", features = ["defmt"] }
embassy-executor = { version = "0.9.0", features = [ "arch-cortex-m", "executor-interrupt", "executor-thread", "defmt" ] }
embassy-time = { version = "0.5.0", features = [ "defmt", "defmt-timestamp-uptime", "tick-hz-32_768" ] }
embassy-usb = { version = "0.5.0", features = [ "defmt" ] }
embassy-embedded-hal = { version = "0.5.0", features = ["defmt"] }
embassy-futures = { version = "0.1.2", features = ["defmt"] }
heapless = { version = "0.9.2", default-features = false }
critical-section = "1.1"

# Defmt for logging
defmt = "1.0.1"
defmt-rtt = "1.0.0"

dw1000 = { git = "https://github.com/jkelleyrtp/dw1000-rs" }

anyhow = { version = "1.0", default-features = false }

[lib]
name = "uwb_anchor"
path = "src/lib.rs"

[workspace.dependencies.reqwest]
version = "0.13"
features = ["blocking"]

# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = "s"

[profile.release]
codegen-units = 1
incremental = false
debug = true
lto = true
opt-level = "s"
