[package]
name = "uwb-tag"
version = "0.1.0"
authors = ["Nicolas Farabegoli <nicolas.farabegoli@gmail.com>"]
edition = "2021"

[features]
default = ["stm32l432kc"]
stm32l432kc = ["embassy-stm32/stm32l432kc"]
stm32f103 = ["embassy-stm32/stm32f103c8"]

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
panic-probe = { workspace = true }
embedded-hal = { workspace = true }
embedded-hal-1 = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-hal-bus = { workspace = true }

# Embassy dependencies
embassy-stm32 = { workspace = true }
embassy-sync = { workspace = true }
embassy-executor = { workspace = true }
embassy-time = { workspace = true }

# Defmt for logging
defmt = { workspace = true }
defmt-rtt = { workspace = true }

dw1000 = { workspace = true }

[build-dependencies]
reqwest = { workspace = true }
