[package]
name = "uwb-tag"
version = "0.1.0"
authors = ["Nicolas Farabegoli <nicolas.farabegoli@gmail.com>"]
edition = "2021"

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
panic-probe = { workspace = true }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-hal-bus = { workspace = true }

# Embassy dependencies
embassy-stm32 = { workspace = true }
embassy-sync = { workspace = true }
embassy-executor = { workspace = true }
embassy-time = { workspace = true }

# Defmt for logging
defmt = { workspace = true }
defmt-rtt = { workspace = true }

dw3000-ng = { workspace = true }
smoltcp = { workspace = true }

uwb-anchor = { path = "..", default-features = false }

[features]
default = ["tag-1"]
tag-1 = []
tag-2 = []
tag-3 = []
tag-4 = []
tag-5 = []
tag-6 = []
tag-7 = []
tag-8 = []
tag-9 = []
tag-10 = []
tag-11 = []
tag-12 = []


[build-dependencies]
reqwest = { workspace = true }
