name: CI/CD Pipeline

on:
  workflow_call:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

permissions: {}

jobs:
  check:
    name: 🧪 Check, Format, Clippy, Docs
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      
      - &install-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf
      
      - &install-arm-toolchain
        name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi
      
      - &cache
        name: Cache cargo registry
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: 📦 Build
        run: cargo build --workspace --all-targets

      - name: 🧹 Format check
        run: cargo fmt --all -- --check

      - name: 🧐 Clippy
        run: cargo clippy --workspace --all-targets

      - name: 📚 Docs check
        run: cargo doc --workspace --no-deps --document-private-items

  release-plz:
    name: 🚀 Release PR & GitHub Release
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'Project-Emerge'
    runs-on: ubuntu-latest
    needs: [ check ]
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - *checkout
      - *install-rust
      - *install-arm-toolchain
      - *cache
      - name: Run release-plz
        uses: release-plz/action@a80d79efe0a195618acb02a4089d55fe74d2505f # v0.5.136
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  success:
    runs-on: ubuntu-latest
    needs: [check, release-plz]
    if: >-
      ${{
        always() && (
          contains(join(needs.*.result, ','), 'failure')
          || !contains(join(needs.*.result, ','), 'cancelled')
        )
      }}
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}